name: Deploy Studio
on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          submodules: recursive

      - uses: actions/setup-node@v3
        with:
          node-version: 16.13.1

      # - name: plugins
      #   run: yarn add umi-plugin-pro

      # - name: fetch-blocks
      #   run: yarn run pro fetch-blocks

      - name: site
        run: cd frontend && yarn && npm run build
        env:
          NODE_ENV: production

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist
          force_orphan: true
